version: "3.9"

services:
  postgres:
    image: docker.io/postgres:16
    restart: always
    container_name: kittybot-db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PWD}
      - POSTGRES_DB=${DB}
    volumes:
      - psql:/var/lib/postgresql/data
    ports:
      - 5432:5432

  kitty:
    build: .
    restart: always
    container_name: kittybot
    depends_on:
      - db
    env_file:
      - .env

volumes:
  psql:
